import { solar, hydro, wind, renewable } from "./imgs";

export const projectDetails = [
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
  {
    img: solar,
    title: "2.415 MW Bundled Solar Power Project",
    location: "Maharashtra and Tamil Nadu, India",
    availableBco2: 1000,
    price: 2,
    sdg: 4,
  },
  {
    img: renewable,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 2000,
    price: 2.3,
    sdg: 6,
  },
  {
    img: wind,
    title: "1.26 MW Ground Mounted Solar Power Project",
    location: "Gujarat , India",
    availableBco2: 2500,
    price: 2,
    sdg: 2,
  },
  {
    img: hydro,
    title: "250 kW Ground Mounted Solar Power Project",
    location: "Himachal Pradesh,India",
    availableBco2: 1000,
    price: 1.2,
    sdg: 4,
  },
];
